acemq:
  initVolumeAsRoot: true
  pki:
    keys: []
    trust: []
  qmname: null
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 2048Mi
aceonly:
  replicaCount: 1
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: "1"
      memory: 1024Mi
arch: amd64
dashboardEnabled: true
dataPVC:
  name: data
  size: 2Gi
  storageClassName: ""
designerFlowsEnabled: false
designerflows:
  resources:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: "1"
      memory: 256Mi
image:
  acemq: cp.icr.io/ibm-ace-mq-server-prod:11.0.0.6
  acemqclient: cp.icr.io/ibm-ace-mqclient-server-prod:11.0.0.6
  aceonly: ACE_ONLY
  configurator: cp.icr.io/ibm-ace-icp-configurator-prod:11.0.0.6
  designerflows: cp.icr.io/ibm-ace-designer-flows-prod:11.0.0.6
  pullPolicy: IfNotPresent
  pullSecret: PULL_SECRET
imageType: ace
integrationServer:
  configurationSecret: null
  defaultAppName: null
  fsGroupGid: null
  keystoreKeyNames: null
  name: null
  truststoreCertNames: null
license: accept
livenessProbe:
  failureThreshold: 1
  initialDelaySeconds: 360
  periodSeconds: 10
  timeoutSeconds: 5
log:
  format: json
metrics:
  enabled: true
odTracingConfig:
  enabled: false
  odAgentImageRepository: cp.icr.io/icp4i-od-agent
  odAgentImageTag: 1.0.0
  odAgentLivenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  odAgentReadinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  odCollectorImageRepository: cp.icr.io/icp4i-od-collector
  odCollectorImageTag: 1.0.0
  odCollectorLivenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  odCollectorReadinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
  odTracingNamespace: null
persistence:
  enabled: false
  useDynamicProvisioning: false
productionDeployment: false
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
sch:
  global:
    image:
      repository: ""
  image:
    name: ibmcom/opencontent-common-utils
    pullPolicy: IfNotPresent
    pullSecret: ""
    tag: 1.1.2
  jobPostDeleteWeight: 2
  jobPostdeleteDeletePolicy: hook-succeeded
  jobPreinstallDeletePolicy: hook-succeeded
  jobPreinstallWeight: -1
  rbac:
    serviceAccountName: ibm-sch-secret-gen
selectedCluster:
- ip: icp-console.devops-gse-state-farm-o-0143c5dd31acd8e030a1d6e0ab1380e3-0001.us-east.containers.appdomain.cloud
  label: local-cluster
  namespace: local-cluster
  value: local-cluster
service:
  customPorts: null
  iP: icp-proxy.devops-gse-state-farm-o-0143c5dd31acd8e030a1d6e0ab1380e3-0001.us-east.containers.appdomain.cloud
  serverlistenerPort: 7800
  serverlistenerTLSPort: 7843
  switchAdminPort: null
  switchAgentCPort: null
  switchAgentPPort: null
  type: NodePort
  webuiPort: 7600
